version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-trademap}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-dbpassword}
    volumes:
      - mongodb_data:/data/db
    networks:
      - posts-api-network

  app:
    build: .
    container_name: posts-api
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER:-trademap}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-dbpassword}
      MONGO_DATABASE: ${MONGO_DATABASE:-posts}
    depends_on:
      - mongodb
    networks:
      - posts-api-network

volumes:
  mongodb_data:
    driver: local

networks:
  posts-api-network:
    name: posts-api-network
    driver: bridge
